name: n8_default_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  mask_text_input_formatter: ^2.4.0
  zoom_tap_animation: ^1.1.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Montserrat-Black.ttf
        - asset: assets/fonts/roboto/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/roboto/Montserrat-Bold.ttf
        - asset: assets/fonts/roboto/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/roboto/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/roboto/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/roboto/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/roboto/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/roboto/Montserrat-Italic.ttf
        - asset: assets/fonts/roboto/Montserrat-Light.ttf
        - asset: assets/fonts/roboto/Montserrat-LightItalic.ttf
        - asset: assets/fonts/roboto/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/roboto/Montserrat-Medium.ttf
        - asset: assets/fonts/roboto/Montserrat-Regular.ttf
        - asset: assets/fonts/roboto/Montserrat-SemiBold.ttf
        - asset: assets/fonts/roboto/Montserrat-Thin.ttf
        - asset: assets/fonts/roboto/Montserrat-ThinItalic.ttf

